### PR TITLE
[Task-14] Added photograph and one line intro of all team members

### PR DESCRIPTION
**Pull request by sanikapareek-contentstack**
Added photographs.
Added one line intro.

### CODE REVIEW

**Review by cs-raj — APPROVED** [review]
Looks Good

**Comment by faraazb** [comment]
Some changes from main are missing.

**Comment by sanikapareek-contentstack** [comment]
> Some changes from main are missing.
Added them please review it.

**Review by faraazb — APPROVED** [review]
Good to go!

**Pull request merged**
